spring.application.name=novaevents
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.datasource.url=jdbc:mysql://localhost:3306/novaevents
spring.datasource.username=75246
spring.datasource.password=senha01
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.mvc.hiddenmethod.filter.enabled=true
spring.jpa.show-sql=true
